# Generated by Django 2.0 on 2019-09-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0002_ministries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/carousels'),
        ),
    ]
