# Generated by Django 2.0 on 2019-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0006_auto_20191001_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='media/events'),
        ),
    ]
