# Generated by Django 2.0 on 2019-11-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0016_auto_20191114_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=128, null=True),
        ),
    ]
