# Generated by Django 2.0 on 2019-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0017_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
