# Generated by Django 2.0 on 2019-11-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0018_auto_20191114_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(max_length=254, upload_to='')),
            ],
        ),
    ]
